plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\rebek\\.vscode\\Sheep managment website test 1\\sheep-management-app\\Becky test\\mainversion_1Sheep-Management-test"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]